name: build-deploy-assets

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: twtug/lkmpg

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Build
        run: |
          make all
          make html
          tar zcvf lkmpg-html.tar.gz ./html
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            lkmpg.pdf
            lkmpg-html.tar.gz
          tag_name: "latest"
          prerelease: true
