name: status-checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: validate coding style and functionality
        run: |
            sudo apt-get install -q -y clang-format-12
            sudo apt-get install -q -y cppcheck
            sudo apt-get install -q -y gcc-11
            .ci/check-format.sh
            .ci/static-analysis.sh
            .ci/build-n-run.sh
        shell: bash
